-- Fichier de création des tables pour la base de données --

drop table LIGNE_COMMANDE;
drop table COMMANDE;
drop table PRODUIT;
drop table UTILISATEUR;
drop table ADRESSE;
drop table CATEGORIE;

CREATE TABLE CATEGORIE ( 
	ID_CATEGORIE int NOT NULL AUTO_INCREMENT , 
	NOM_CATEGORIE varchar(30) NOT NULL,
	PRIMARY KEY (ID_CATEGORIE)
) ;

CREATE TABLE PRODUIT ( 
	ID_PRODUIT int NOT NULL AUTO_INCREMENT , 
	NOM_PRODUIT varchar(50) NOT NULL,
	DESCRIPTION text(2000) NOT NULL,
	CATEGORIE int NOT NULL,
	PRIX float(6,2) NOT NULL,
	TAXE float(4,2) NOT NULL,
	IMAGE varchar(100) NOT NULL,
	ALT varchar(50) NOT NULL,
	PRIMARY KEY (ID_PRODUIT),
	FOREIGN KEY (CATEGORIE) REFERENCES CATEGORIE(ID_CATEGORIE)
) ;

CREATE TABLE ADRESSE (
	ID_ADRESSE int NOT NULL AUTO_INCREMENT ,
	NUMERO_CIVIQUE int NOT NULL,
	RUE varchar(100) NOT NULL,
	VILLE varchar(50) NOT NULL,
	REGION varchar(50) NOT NULL,
	PAYS varchar(50) NOT NULL,
	DEPARTEMENT varchar(10) NOT NULL,
	PRIMARY KEY (ID_ADRESSE)
) ;

CREATE TABLE UTILISATEUR (
	ID_UTILISATEUR int NOT NULL AUTO_INCREMENT , 
	PSEUDO varchar(50) NOT NULL,
	MDP varchar(50) NOT NULL,
	ROLE varchar(20) NOT NULL,
	NOM_CLIENT varchar(50) NOT NULL,
	PRENOM_CLIENT varchar(50) NOT NULL,
	ADRESSE int NULL,
	COURRIEL varchar(100) NOT NULL,
	TELEPHONE varchar(15) NULL,
	PRIMARY KEY (ID_UTILISATEUR),
	FOREIGN KEY (ADRESSE) REFERENCES ADRESSE(ID_ADRESSE),
	CONSTRAINT CHK_ROLE_CLIENT CHECK (ROLE='CLIENT' OR ROLE='ADMINISTRATEUR')
) ;

CREATE TABLE COMMANDE (
	ID_COMMANDE int NOT NULL AUTO_INCREMENT , 
	DATE_COMMANDE date NOT NULL,
        ID_CLIENT int NOT NULL,
        PRIMARY KEY (ID_COMMANDE),
        FOREIGN KEY (ID_CLIENT) REFERENCES UTILISATEUR(ID_UTILISATEUR)
) ;

CREATE TABLE LIGNE_COMMANDE (
        ID_COMMANDE int NOT NULL,
        ID_PRODUIT int NOT NULL,
        QUANTITEE int NOT NULL,
        PRIMARY KEY (ID_COMMANDE, ID_PRODUIT),
        FOREIGN KEY (ID_COMMANDE) REFERENCES COMMANDE(ID_COMMANDE),
        FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT)
) ;

